name: "Auto Format"

on:
  workflow_dispatch:
  schedule:
    # 開発の動きがない時間を想定し、毎日午前 6 時に実施
    - cron: '0 21 * * *'

jobs:
  format:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.9.0
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Clean install using pnpm
        shell: bash
        run: pnpm install --no-frozen-lockfile

      - name: Run prettier
        shell: bash
        run: pnpm run format

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: ':recycle: Auto format'
          committer: GitHub <noreply@github.com>
          author: albelium-bot[bot] <154823176+albelium-bot[bot]@users.noreply.github.com>
          signoff: false
          title: ':recycle: Auto Format'
          body: 'This was automatically generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
          labels: |
            ignore-for-release
          base: 'main'
          branch: 'workflow/auto-format'
          branch-suffix: 'short-commit-hash'
