name: "Preview"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-22.04

    outputs:
      publish-docs: ${{ steps.needs.outputs.publish-docs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            publish-docs:
              - 'apps/docs/**/*'
              - 'package.json'
      - name: Output Needs
        id: needs
        run: |
          echo "publish-docs=${{ steps.changes.outputs.publish-docs == 'true' }}" >> $GITHUB_OUTPUT

  publish-docs:
    runs-on: ubuntu-22.04
    needs: filter
    if: needs.filter.outputs.publish-docs == 'true'

    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.6.2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Clean install using pnpm
        shell: bash
        run: pnpm install --filter=docs --frozen-lockfile

      - name: Build
        run: pnpm run build --filter=docs

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        id: cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: web-application-template-docs
          directory: ./apps/docs/build
          gitHubToken: ${{ steps.app-token.outputs.token }}
          branch: preview${{ github.ref }}
