name: "Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  # 手動実行か否か
  IS_DISPATCH: ${{ contains(fromJSON('["workflow_dispatch"]'), github.event_name) }}

jobs:
  changed:
    runs-on: ubuntu-22.04

    outputs:
      docs: ${{ steps.needs.outputs.docs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v3.0.0
        id: changes
        with:
          filters: |
            docs:
              - 'apps/docs/**/*'
              - 'package.json'
      - name: Output Needs
        id: needs
        run: |
          echo "docs=${{ env.IS_DISPATCH == 'true' || steps.changes.outputs.docs == 'true' }}" >> $GITHUB_OUTPUT

  publish-docs:
    runs-on: ubuntu-22.04
    needs: changed
    if: needs.changed.outputs.docs == 'true'

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.8.0
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Clean install using pnpm
        shell: bash
        run: pnpm install --filter=docs --frozen-lockfile

      - name: Build
        run: pnpm run build --filter=docs

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        id: cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: web-application-template-docs
          directory: ./apps/docs/dist
          gitHubToken: ${{ steps.app-token.outputs.token }}
          branch: main
